COS-19: Update sync information when changes are made to a contribution
compucorp/uk.co.compucorp.odoosync pull request #12
Opened 2018-04-27 10:38 UTC by awg-github

1. If a contribution is created or updated before it is synced:
- its "Sync Status" field is filled with "Awaiting Sync"
- its "Action to Sync" field is filled with "Create"
- its "Action Date" field is filled with the timestamp when the contribution is created.
![cos-19 createupdate contribution](https://user-images.githubusercontent.com/36959503/39358775-edd39f14-4a1f-11e8-8ad8-e5761f4cbb74.gif)

2. If a contribution's status is updated/ a payment has been made to it/ a line item is added, updated or removed: 
- its "Sync Status" is filled with "Awaiting Sync"
- its "Action to Sync" field is filled with the option corresponding to its current status
- its "Action Date" field is filled with the timestamp when the contribution is created
![cos19 contribution status update](https://user-images.githubusercontent.com/36959503/39358793-0dd1460e-4a20-11e8-9ec3-f6a88c205f82.gif)

2018-04-30 10:13 UTC, guanhuan commented
All looks good. I think I made a small mistake in the spec regarding the action date in the update case. I left a comment in the ticket https://compucorp.atlassian.net/browse/COS-19?focusedCommentId=69725&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-69725. Would you be able to have a look?

2018-04-30 18:44 UTC, omarabuhussein requested changes

2018-04-30 18:44 UTC, omarabuhussein commented on odoosync.php
> +  $contributionSyncInformationUpdater = new CRM_Odoosync_Hook_Pre_ContributionProcessesHandler($op, $objectName, $id, $params);
looking at this now, I think there is inconsistent implementation here, because for the contact entity you use form level hook which is **hook_civicrm_postProcess** but for contribution entity you are using pre and post hooks which are database level hooks, Is there any reason for that ? 

 I think the contact entity must be changed to follow that too similar to the contribution entity. but if we agreed to do this then it  should be done in another PR and not in this one.

2018-04-30 18:44 UTC, omarabuhussein commented on CRM/Odoosync/Hook/Pre/ContributionProcessesHandler.php
> +  private function isContributionEditProcess() {
I would rename this to just : 
isContributionEdit

2018-04-30 18:44 UTC, omarabuhussein commented on CRM/Odoosync/Hook/Pre/ContributionProcessesHandler.php
> +    if (!$this->isContributionEditProcess()) {
I think it is better to move the logic in this method to a new one and call it : 

updateContributionSyncInfoOnStatusChange

so this method would only call it : 

```php
$this->updateContributionSyncInfoOnStatusChange();
```

2018-04-30 18:44 UTC, omarabuhussein commented on CRM/Odoosync/Hook/Pre/ContributionProcessesHandler.php
> +    $oldContributionStatus = $this->params['prevContribution']->contribution_status_id;
I would move the following lines : 

```php
    $oldContributionStatus = $this->params['prevContribution']->contribution_status_id;
    $newContributionStatus = $this->params['contribution_status_id'];
    $isStatusChanged = (int) $oldContributionStatus != (int) $newContributionStatus;

```

to a new method and call it : 

if($this->isContributionStatusChanged())

2018-04-30 18:44 UTC, omarabuhussein commented on CRM/Odoosync/Hook/Pre/ContributionProcessesHandler.php
> +      $actionToSync = (new CRM_Odoosync_Contribution_StatusMapping())->getActionByContributionStatusId($newContributionStatus);
I did not checked the logic in (CRM_Odoosync_Contribution_StatusMapping) class yet, but I think it is probably better to change its methods to be static.

2018-04-30 18:44 UTC, omarabuhussein commented on CRM/Odoosync/Hook/Pre/ContributionProcessesHandler.php
> +class CRM_Odoosync_Hook_Pre_ContributionProcessesHandler {
no need for **ProcessesHandler** part in the class name, same for CRM_Odoosync_Hook_Post_ContributionProcessesHandler

2018-04-30 18:44 UTC, omarabuhussein commented on CRM/Odoosync/Hook/Pre/ContributionProcessesHandler.php
> +  public function handleHook() {
I think renaming this method to **process** instead of **handleHook** is better. same for CRM_Odoosync_Hook_Post_ContributionProcessesHandler

2018-04-30 18:44 UTC, omarabuhussein commented on CRM/Odoosync/Contribution/SyncInformation.php
> +class CRM_Odoosync_Contribution_SyncInformation {
I think a better name for this class is : 

CRM_Odoosync_Contribution_SyncInformationUpdater

2018-04-30 18:44 UTC, omarabuhussein commented on CRM/Odoosync/Hook/Post/ContributionProcessesHandler.php
> +      && $this->objectRef->entity_table == 'civicrm_contribution'
but the line item could be for a membership or other type of tables but at the end it is attached to a contribution, so I think this check : 

```php
&& isset($this->objectRef->entity_table)
&& $this->objectRef->entity_table == 'civicrm_contribution'
```

is not needed

2018-04-30 18:44 UTC, omarabuhussein commented on CRM/Odoosync/Hook/Post/ContributionProcessesHandler.php
> +class CRM_Odoosync_Hook_Post_ContributionProcessesHandler {
I think it is better to seperate this class into three classes : 

CRM_Odoosync_Hook_Post_Contribution

CRM_Odoosync_Hook_Post_LineItem

CRM_Odoosync_Hook_Post_EntityFinancialTrxn

and move the related logic in each class .

also I think checking the entity type and operation could be moved to the hook itself implementation (inside odoosync.php file ) before creating the class instance

2018-04-30 18:44 UTC, omarabuhussein commented on CRM/Odoosync/Hook/Post/ContributionProcessesHandler.php
> +      if ($this->operation == 'create') {
the logic for both create and edit cases looks the same to me (or am I mistaken ?), so I think they can just be combined togther.

2018-04-30 18:44 UTC, omarabuhussein commented on CRM/Odoosync/Hook/Post/ContributionProcessesHandler.php
> +  private function getContributionId($civicrmFinancialItemId) {
you can use civicrm API here instead of direct SQL query.

2018-04-30 18:44 UTC, omarabuhussein commented on CRM/Odoosync/Hook/Post/ContributionProcessesHandler.php
> +      SELECT * FROM odoo_invoice_sync_information AS sync_info
please use civicrm API to fetch the option value and then use it in the query instead of use the join.

2018-04-30 18:44 UTC, omarabuhussein commented on CRM/Odoosync/Contribution/SyncInformation.php
> +    if ($this->isContributionCreated()) {
I think a more clear name for this method is : isContributionSyncInfoCreated

2018-04-30 18:44 UTC, omarabuhussein commented on CRM/Odoosync/Contribution/SyncInformation.php
> +        LEFT JOIN civicrm_option_value AS action_option
please and instead of using join on civicrm_option_group and civicrm_option_value  tables, fetch the values using the API then use them in the query. same for create() method.

2018-04-30 18:44 UTC, omarabuhussein commented on CRM/Odoosync/Contribution/StatusMapping.php
> +    return CRM_Core_PseudoConstant::getName(
please use civicrm API

2018-04-30 18:44 UTC, omarabuhussein commented on CRM/Odoosync/Contribution/StatusMapping.php
> +class CRM_Odoosync_Contribution_StatusMapping {
maybe a more clear name is : 

CRM_Odoosync_Contribution_StatusToSyncActionMapper

2018-05-03 15:19 UTC, awg-github commented on CRM/Odoosync/Hook/Post/ContributionProcessesHandler.php
> +      && $this->objectRef->entity_table == 'civicrm_contribution'
these part is required to validate entity

2018-05-03 15:21 UTC, awg-github commented on odoosync.php
> +  $contributionSyncInformationUpdater = new CRM_Odoosync_Hook_Pre_ContributionProcessesHandler($op, $objectName, $id, $params);
Yes, you are right. Let's change contact functionality in a new PR

2018-05-04 10:56 UTC, omarabuhussein approved these changes

2018-05-04 12:04 UTC, merged