COS-20: Add timezone offset to timestamp in API call when Sync from CiviCRm to Odoo.
compucorp/uk.co.compucorp.odoosync pull request #31
Opened 2018-06-11 16:49 UTC by awg-github

Add timezone offset to timestamp in API call when Sync from CiviCRm to Odoo for the next fields:
1. 'date_invoice' in 'contribution param' block
2. 'payment_date' in 'payment' block
3. 'date' in 'refund' block

2018-06-13 09:56 UTC, omarabuhussein requested changes

2018-06-13 09:56 UTC, omarabuhussein commented on CRM/Odoosync/Sync/Contribution/Data/ContributionParam.php
>      $actionDateTimestamp = $this->getActionDateTimestamp($contributionData->action_date);
what about $actionDateTimestamp ?

2018-06-13 09:56 UTC, omarabuhussein commented on CRM/Odoosync/Sync/Contribution/Data/Payment.php
> +      $paymentDate = CRM_Odoosync_Common_Date::convertDateToTimestamp($paymentItemsDao->payment_date);
maybe it is better to change : 

convertDateToTimestamp() 

method to to the conversion internally ?

2018-06-14 11:20 UTC, awg-github commented on CRM/Odoosync/Sync/Contribution/Data/ContributionParam.php
>      $actionDateTimestamp = $this->getActionDateTimestamp($contributionData->action_date);
We don't need to change it.

2018-06-14 11:23 UTC, awg-github commented on CRM/Odoosync/Sync/Contribution/Data/Payment.php
> +      $paymentDate = CRM_Odoosync_Common_Date::convertDateToTimestamp($paymentItemsDao->payment_date);
We don't do that because this method is used in other cases too.

2018-06-14 14:32 UTC, omarabuhussein approved these changes

2018-06-14 14:56 UTC, merged